const nextPublicEnv: Record<string, string | undefined> = {
  NEXT_PUBLIC_BASE_URL: process.env.NEXT_PUBLIC_BASE_URL,
  NEXT_PUBLIC_COMPANY_NAME: process.env.NEXT_PUBLIC_COMPANY_NAME,
  NEXT_PUBLIC_SITE_TAGLINE: process.env.NEXT_PUBLIC_SITE_TAGLINE,
  NEXT_PUBLIC_SITE_DESCRIPTION: process.env.NEXT_PUBLIC_SITE_DESCRIPTION,
  NEXT_PUBLIC_CONTACT_EMAIL: process.env.NEXT_PUBLIC_CONTACT_EMAIL,
  NEXT_PUBLIC_CONTACT_PHONE: process.env.NEXT_PUBLIC_CONTACT_PHONE,
  NEXT_PUBLIC_SOCIAL_TWITTER: process.env.NEXT_PUBLIC_SOCIAL_TWITTER,
  NEXT_PUBLIC_SOCIAL_LINKEDIN: process.env.NEXT_PUBLIC_SOCIAL_LINKEDIN,
  NEXT_PUBLIC_SOCIAL_GITHUB: process.env.NEXT_PUBLIC_SOCIAL_GITHUB,
  NEXT_PUBLIC_SOCIAL_FACEBOOK: process.env.NEXT_PUBLIC_SOCIAL_FACEBOOK,
  NEXT_PUBLIC_INSTAGRAM_URL: process.env.NEXT_PUBLIC_INSTAGRAM_URL,
  NEXT_PUBLIC_ADDRESS_STREET: process.env.NEXT_PUBLIC_ADDRESS_STREET,
  NEXT_PUBLIC_ADDRESS_CITY: process.env.NEXT_PUBLIC_ADDRESS_CITY,
  NEXT_PUBLIC_ADDRESS_REGION: process.env.NEXT_PUBLIC_ADDRESS_REGION,
  NEXT_PUBLIC_ADDRESS_POSTAL_CODE: process.env.NEXT_PUBLIC_ADDRESS_POSTAL_CODE,
  NEXT_PUBLIC_ADDRESS_COUNTRY: process.env.NEXT_PUBLIC_ADDRESS_COUNTRY,
};

export const env = (key: string) => {
  const value = nextPublicEnv[key];
  return value && value.trim() !== '' ? value : undefined;
};

export const siteConfig = {
  contact: {
    email: env('NEXT_PUBLIC_CONTACT_EMAIL'),
    phone: env('NEXT_PUBLIC_CONTACT_PHONE'),
  },
  social: {
    twitter: env('NEXT_PUBLIC_SOCIAL_TWITTER'),
    linkedin: env('NEXT_PUBLIC_SOCIAL_LINKEDIN'),
    github: env('NEXT_PUBLIC_SOCIAL_GITHUB'),
    facebook: env('NEXT_PUBLIC_SOCIAL_FACEBOOK'),
    instagram: env('NEXT_PUBLIC_INSTAGRAM_URL'),
  },
};
